variables:
  CHOCOLATEY_CACHE_DIR: $(Pipeline.Workspace)\chocolatey_cache
  CHOCOLATEY_REPO: 'https://pkgs.dev.azure.com/edmcman/choco-vc/_packaging/choco-vc@Local/nuget/v2'

jobs:
- template: azure-pipelines/Build_Exes.yaml
  parameters:
    name: "vs2008"
    chocoPackages:
    - "msvisualcpp-2008sp1express"
    displayName: "Visual C++ Express 2008"
    cmakeGenName: "Visual Studio 9 2008"


# https://cmake.org/cmake/help/latest/generator/Visual%20Studio%2010%202010.html
- template: azure-pipelines/Build_Exes.yaml
  parameters:
    name: "vs2010"
    chocoPackages:
    - "msvisualcpp-2010express"
    displayName: "Visual C++ Express 2010"
    cmakeGenName: "Visual Studio 12 2013"
    cmakeGenToolsetArg: "-T v100"

# - template: azure-pipelines/Build_Exes.yaml
#   parameters:
#     name: "vs2012p"
#     chocoPackages:
#     - "msvisualstudio-2012professional"
#     displayName: "Visual C++ Professional 2012"
#     cmakeGenName: "Visual Studio 11 2012"

- template: azure-pipelines/Build_Exes.yaml
  parameters:
    name: "vs2012"
    chocoPackages:
    - "msvisualstudio-2012express"
    displayName: "Visual C++ Express 2012"
    cmakeGenName: "Visual Studio 11 2012"

- template: azure-pipelines/Build_Exes.yaml
  parameters:
    name: "vs2013"
    chocoPackages:
    - "msvisualstudio-2013express"
    displayName: "Visual C++ Express 2013"
    cmakeGenName: "Visual Studio 12 2013"

- template: azure-pipelines/Build_Exes.yaml
  parameters:
    name: "vs2015"
    chocoPackages:
    - "msvisualstudio-2015community"
    displayName: "Visual C++ 2015"
    cmakeGenName: "Visual Studio 14 2015"

- template: azure-pipelines/Build_Exes.yaml
  parameters:
    name: "vs2017"
    chocoPackages: []
    displayName: "Visual C++ 2017"
    cmakeGenName: "Visual Studio 15 2017"
    vmImage: "vs2017-win2016"

- template: azure-pipelines/Build_Exes.yaml
  parameters:
    name: "vs2019"
    # A hack because VS2019 is already installed on these machines
    chocoPackages: []
    displayName: "Visual C++ 2019"
    cmakeGenName: "Visual Studio 16 2019"
