parameters:
- name: vsVersionList
  type: object
  default:
    - name: "vs2008"
      chocoPackages:
        - "msvisualcpp-2008sp1express"
      displayName: "Visual C++ Express 2008"
      cmakeGenName: "Visual Studio 9 2008"
- name: archList
  type: object
  default:
    - 'WIN32'
    - 'X64'

variables:
  CHOCOLATEY_CACHE_DIR: $(Pipeline.Workspace)\chocolatey_cache
  CHOCOLATEY_REPO: 'https://pkgs.dev.azure.com/edmcman/choco-vc/_packaging/choco-vc@Local/nuget/v2'

jobs:
  - ${{ each vsVersion in parameters.vsVersionList }}:
    - ${{ each arch in parameters.archList }}:
      - job: ${{ vsVersion }}_${{ arch }}
        variables:
          vsVersion: ${{ vsVersion }}
          arch: ${{ arch }}
          # Additional version-specific variables can be set here based on vsVersion
        steps:
        - template: azure-pipelines/Build_Exes.yaml
          parameters:
            name: ${{ vsVersion }}_${{ arch }}
            arch: ${{ arch }}
            chocoPackages: ${{ vsVersion.chocoPackages }}
            displayName: ${{ vsVersion.displayName }}
            cmakeGenName: ${{ vsVersion.cmakeGenName }}
            cmakeGenToolsetArg: ${{ vsVersion.cmakeGenToolsetArg }}
            extraPath: ${{ vsVersion.extraPath }}
