variables:
  CHOCLATEY_CACHE_DIR: $(Pipeline.Workspace)/choclatey_cache

jobs:
- template: azure-pipelines/Build_Exes.yaml
  parameters:
    name: "vs2008"
    chocoPackages:
    - "msvisualcpp-2008sp1express"
    chocoFlags: "--source https://pkgs.dev.azure.com/edmcman/choco-vc/_packaging/choco-vc%40Local/nuget/v2"
    displayName: "Visual C++ Express 2008"
    cmakeGenName: "Visual Studio 9 2008"

- template: azure-pipelines/Build_Exes.yaml
  parameters:
    name: "vs2010"
    chocoPackages:
    - "vcexpress2010"
    displayName: "Visual C++ Express 2010"
    cmakeGenName: "Visual Studio 10 2010"

- template: azure-pipelines/Build_Exes.yaml
  parameters:
    name: "vs2012"
    chocoPackages:
    - "visualstudio2012wdx"
    displayName: "Visual C++ 2012"
    cmakeGenName: "Visual Studio 11 2012"

- template: azure-pipelines/Build_Exes.yaml
  parameters:
    name: "vs2013"
    chocoPackages:
    - "visualstudioexpress2013windowsdesktop"
    displayName: "Visual C++ 2013"
    cmakeGenName: "Visual Studio 12 2013"

- template: azure-pipelines/Build_Exes.yaml
  parameters:
    name: "vs2015"
    chocoPackages:
    - "visualcppbuildtools"
    displayName: "Visual C++ 2015"
    cmakeGenName: "Visual Studio 14 2015"

- template: azure-pipelines/Build_Exes.yaml
  parameters:
    name: "vs2017"
    chocoPackages: []
    displayName: "Visual C++ 2017"
    cmakeGenName: "Visual Studio 15 2017"
    vmImage: "vs2017-win2016"

- template: azure-pipelines/Build_Exes.yaml
  parameters:
    name: "vs2019"
    # A hack because VS2019 is already installed on these machines
    chocoPackages: []
    displayName: "Visual C++ 2019"
    cmakeGenName: "Visual Studio 16 2019"
