parameters:
- name: vsVersionList
  type: object
  default:
    - name: "vs2008"
      chocoPackages:
        - "msvisualcpp-2008sp1express"
      displayName: "Visual C++ Express 2008"
      cmakeGenName: "Visual Studio 9 2008"
      has64: false

    - name: "vs2010"
      chocoPackages:
        - "msvisualcpp-2010express"
      displayName: "Visual C++ Express 2010"
      cmakeGenName: "Visual Studio 12 2013"
      cmakeGenToolsetArg: "-T v100"
      extraPath: "%SystemRoot%\\Microsoft.NET\\Framework\\v4.0.30319"
      has64: false

    - name: "vs2012"
      chocoPackages:
        - "msvisualstudio-2012express"
      displayName: "Visual C++ Express 2012"
      cmakeGenName: "Visual Studio 11 2012"

    - name: "vs2013"
      chocoPackages:
        - "msvisualstudio-2013express"
      displayName: "Visual C++ Express 2013"
      cmakeGenName: "Visual Studio 12 2013"

    - name: "vs2015"
      chocoPackages:
        - "msvisualstudio-2015community"
      displayName: "Visual C++ 2015"
      cmakeGenName: "Visual Studio 14 2015"

    - name: "vs2017"
      chocoPackages:
        - "visualstudio2017buildtools"
        - "visualstudio2017-workload-vctools"
      displayName: "Visual C++ 2017"
      cmakeGenName: "Visual Studio 15 2017"

    # vs 2019 isn't working right now for unknown reasons
    #- name: "vs2019"
    #  # A hack because VS2019 is already installed on these machines
    #  chocoPackages: []
    #  displayName: "Visual C++ 2019"
    #  cmakeGenName: "Visual Studio 16 2019"
    #  vmImage: "windows-2019"

    - name: "vs2022"
      # A hack because VS2019 is already installed on these machines
      chocoPackages: []
      displayName: "Visual C++ 2022"
      cmakeGenName: "Visual Studio 17 2022"
      vmImage: "windows-2022"

- name: archList
  type: object
  default:
    - name: 'x86'
      displayName: 'x86'
      cmakeArch: 'win32'

    - name: 'x86_64'
      displayName: 'x86-64'
      cmakeArch: 'x64'

variables:
  CHOCOLATEY_CACHE_DIR: $(Pipeline.Workspace)\chocolatey_cache
  CHOCOLATEY_REPO: 'https://pkgs.dev.azure.com/edmcman/choco-vc/_packaging/choco-vc@Local/nuget/v2'

jobs:
- ${{ each vsVersion in parameters.vsVersionList }}:
  - ${{ each arch in parameters.archList }}:
    - ${{ if not(and(eq(parameters.has64, false), eq(arch.name, 'x86_64'))) }}:
      - template: azure-pipelines/Build_Exes.yaml
        parameters:
          name: ${{ vsVersion.name }}_${{ arch.name }}
          #arch: ${{ arch.name }}
          chocoPackages: ${{ vsVersion.chocoPackages }}
          displayName: ${{ vsVersion.displayName }} ${{ arch.displayName }}
          cmakeAlwaysFlags: -A ${{ arch.cmakeArch }}
          cmakeGenName: ${{ vsVersion.cmakeGenName }}
          cmakeGenToolsetArg: ${{ vsVersion.cmakeGenToolsetArg }}
          extraPath: ${{ vsVersion.extraPath }}
